---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Install python3-systemd
  ansible.builtin.apt:
    name: python3-systemd
    state: present

- name: Copy jail.local configuration
  ansible.builtin.template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
