---
- name: Setup base defaults
  hosts: basics_hosts
  become: true
  pre_tasks:
    - name: Disable unattended upgrades service
      ansible.builtin.service:
        name: unattended-upgrades
        state: stopped
        enabled: no

    - import_tasks: tasks/apt.yml

  tasks:
    - import_tasks: tasks/ssh.yml

    - import_tasks: tasks/ufw.yml

    - import_tasks: tasks/fail2ban.yml

    - import_tasks: tasks/ntp.yml

    - import_tasks: tasks/motd.yml

  post_tasks:
    - name: Enable unattended upgrades service
      ansible.builtin.service:
        name: unattended-upgrades
        state: started
        enabled: yes

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Restart ufw
      ansible.builtin.service:
        name: ufw
        state: restarted

    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
